'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Copy, Download, FileText, CheckCircle } from 'lucide-react';
import styles from './foia.module.css';

type State = 'virginia' | 'maryland' | 'nc' | 'dc';

const stateInfo = {
  virginia: {
    label: 'Virginia (VFOIA)',
    law: 'Virginia Freedom of Information Act, Va. Code § 2.2-3700 et seq.',
    deadline: '5 business days to respond; may request 7-day extension',
    fee: 'Reasonable costs; first 2 hours of search free',
    contact: 'Agency\'s FOIA Officer',
    exemptions: 'Personnel records, ongoing investigations, attorney-client privilege, trade secrets',
  },
  maryland: {
    label: 'Maryland (MPIA)',
    law: 'Maryland Public Information Act, Md. Code, Gen. Prov. § 4-101 et seq.',
    deadline: '10 business days to respond',
    fee: 'Up to $0.10/page; search fees if over 2 hours',
    contact: 'Custodian of Records',
    exemptions: 'Personnel records, police investigative files, medical records, trade secrets',
  },
  nc: {
    label: 'North Carolina (NCPRA)',
    law: 'North Carolina Public Records Act, N.C.G.S. § 132-1 et seq.',
    deadline: 'Reasonable time (no statutory deadline)',
    fee: 'Actual cost of reproduction',
    contact: 'Custodian of public records',
    exemptions: 'Personnel files, criminal investigation records, attorney-client materials',
  },
  dc: {
    label: 'Washington DC (DC FOIA)',
    law: 'District of Columbia Freedom of Information Act, D.C. Code § 2-531 et seq.',
    deadline: '15 business days to respond',
    fee: '$0.25/page after first 100 pages; search fee waived for news/public interest',
    contact: 'Freedom of Information Officer',
    exemptions: 'Personnel files, law enforcement records, trade secrets, deliberative process',
  },
};

function buildLetter(state: State, fields: Record<string, string>): string {
  const info = stateInfo[state];
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const requesterName = fields.requesterName || '[YOUR NAME]';
  const requesterAddress = fields.requesterAddress || '[YOUR ADDRESS]';
  const agencyName = fields.agencyName || '[AGENCY NAME]';
  const agencyAddress = fields.agencyAddress || '[AGENCY ADDRESS]';
  const recordsDescription = fields.recordsDescription || '[DESCRIPTION OF RECORDS REQUESTED]';
  const dateRange = fields.dateRange || '[DATE RANGE]';
  const purpose = fields.purpose || 'public interest research and community accountability';

  return `${today}

${agencyName}
ATTN: ${info.contact}
${agencyAddress}

RE: ${info.label} Request — Public Records

To Whom It May Concern:

Pursuant to the ${info.law}, I hereby request access to and/or copies of the following public records:

RECORDS REQUESTED:
${recordsDescription}

DATE RANGE: ${dateRange}

I am requesting these records for the purpose of ${purpose}.

STATUTORY BASIS:
This request is made pursuant to ${info.law}. Under this law, ${info.deadline}. I understand that ${info.exemptions} may be exempt, but I request that any non-exempt portions be produced and that a detailed exemption log be provided for any withheld material.

FEE WAIVER REQUEST:
I request a waiver of all fees associated with this request on the grounds that disclosure is in the public interest and will contribute significantly to public understanding of government operations. If a fee waiver is denied, please notify me before incurring any costs exceeding $25.00.

If any portion of this request is denied, please provide a written explanation citing the specific statutory exemption(s) relied upon, and advise me of my right to appeal.

Please provide the records in electronic format if available.

Sincerely,

${requesterName}
${requesterAddress}

---
Generated by IRN FOIA Tool · injusticereformnetwork.org/foia
This letter is a template. Review before sending. IRN is not a law firm and this is not legal advice.`;
}

export default function FOIAContent() {
  const [state, setState] = useState<State>('virginia');
  const [fields, setFields] = useState({
    requesterName: '',
    requesterAddress: '',
    agencyName: '',
    agencyAddress: '',
    recordsDescription: '',
    dateRange: '',
    purpose: '',
  });
  const [generated, setGenerated] = useState(false);
  const [copied, setCopied] = useState(false);

  const letter = buildLetter(state, fields);

  function handleGenerate() { setGenerated(true); }

  function handleCopy() {
    navigator.clipboard.writeText(letter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  function handleDownload() {
    const blob = new Blob([letter], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `irn-foia-${state}-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function set(k: string, v: string) { setFields(p => ({ ...p, [k]: v })); }

  const info = stateInfo[state];

  return (
    <main id="main-content" className={styles.main}>
      <div className={styles.accentBar} aria-hidden="true" />

      <header className={styles.hero}>
        <div className={styles.container}>
          <motion.span className={styles.kicker} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
            Self-Serve Tool
          </motion.span>
          <motion.h1 className={styles.heroTitle} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
            FOIA Request Generator
          </motion.h1>
          <motion.p className={styles.heroSubtitle} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }}>
            Fill in the fields below — get a ready-to-send public records request letter for Virginia, Maryland, North Carolina, or DC. Free. No account required.
          </motion.p>
        </div>
      </header>

      <section className={styles.section}>
        <div className={styles.container}>
          <div className={styles.layout}>

            {/* FORM */}
            <div className={styles.formCol}>
              <div className={styles.formCard}>
                <h2 className={styles.formTitle}>Build Your Request</h2>

                {/* State selector */}
                <div className={styles.field}>
                  <label className={styles.label}>Jurisdiction</label>
                  <div className={styles.stateGrid}>
                    {(Object.keys(stateInfo) as State[]).map(s => (
                      <button
                        key={s}
                        type="button"
                        className={`${styles.stateBtn} ${state === s ? styles.stateBtnActive : ''}`}
                        onClick={() => setState(s)}
                      >
                        {stateInfo[s].label.split(' (')[0]}
                      </button>
                    ))}
                  </div>
                </div>

                <div className={styles.lawNote}>
                  <span className={styles.lawLabel}>Governing Law</span>
                  <span className={styles.lawText}>{info.law}</span>
                  <span className={styles.lawMeta}>{info.deadline}</span>
                </div>

                <div className={styles.fieldRow}>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="requesterName">Your name (or alias)</label>
                    <input id="requesterName" type="text" className={styles.input} placeholder="Jane Doe" value={fields.requesterName} onChange={e => set('requesterName', e.target.value)} />
                  </div>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="requesterAddress">Your mailing address</label>
                    <input id="requesterAddress" type="text" className={styles.input} placeholder="123 Main St, City, State ZIP" value={fields.requesterAddress} onChange={e => set('requesterAddress', e.target.value)} />
                  </div>
                </div>

                <div className={styles.fieldRow}>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="agencyName">Agency name <span className={styles.req}>*</span></label>
                    <input id="agencyName" type="text" className={styles.input} placeholder="Newport News Police Department" value={fields.agencyName} onChange={e => set('agencyName', e.target.value)} />
                  </div>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="agencyAddress">Agency address</label>
                    <input id="agencyAddress" type="text" className={styles.input} placeholder="9710 Jefferson Ave, Newport News, VA" value={fields.agencyAddress} onChange={e => set('agencyAddress', e.target.value)} />
                  </div>
                </div>

                <div className={styles.field}>
                  <label className={styles.label} htmlFor="recordsDescription">Records requested <span className={styles.req}>*</span></label>
                  <textarea id="recordsDescription" className={styles.textarea} rows={4}
                    placeholder="Be specific: e.g. 'All use-of-force reports, body camera footage, and incident reports involving Officer [Name/Badge #] from January 1, 2025 to present.'"
                    value={fields.recordsDescription} onChange={e => set('recordsDescription', e.target.value)} />
                </div>

                <div className={styles.fieldRow}>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="dateRange">Date range</label>
                    <input id="dateRange" type="text" className={styles.input} placeholder="January 1, 2024 to present" value={fields.dateRange} onChange={e => set('dateRange', e.target.value)} />
                  </div>
                  <div className={styles.field}>
                    <label className={styles.label} htmlFor="purpose">Purpose (optional)</label>
                    <input id="purpose" type="text" className={styles.input} placeholder="community accountability research" value={fields.purpose} onChange={e => set('purpose', e.target.value)} />
                  </div>
                </div>

                <button type="button" className={styles.generateBtn} onClick={handleGenerate}>
                  <FileText size={15} aria-hidden="true" /> Generate Letter
                </button>
              </div>
            </div>

            {/* PREVIEW */}
            <div className={styles.previewCol}>
              <div className={styles.previewCard}>
                <div className={styles.previewHeader}>
                  <span className={styles.previewLabel}>
                    {generated ? <><CheckCircle size={13} aria-hidden="true" /> Letter Ready</> : 'Preview'}
                  </span>
                  {generated && (
                    <div className={styles.previewActions}>
                      <button type="button" className={styles.previewBtn} onClick={handleCopy}>
                        <Copy size={13} aria-hidden="true" /> {copied ? 'Copied!' : 'Copy'}
                      </button>
                      <button type="button" className={styles.previewBtn} onClick={handleDownload}>
                        <Download size={13} aria-hidden="true" /> Download
                      </button>
                    </div>
                  )}
                </div>
                <pre className={styles.letterPre}>{letter}</pre>
              </div>
            </div>

          </div>
        </div>
      </section>
    </main>
  );
}
